apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-file-store
  labels:
    app: backend-file-store
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-file-store
  template:
    metadata:
      labels:
        app: backend-file-store
    spec:
      containers:
      - name: backend-file-store
        image: <your-docker-hub-username>/backend-file-store:latest  # Replace with your Docker image
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /app/storage
          name: storage-volume
        env:
        - name: FLASK_ENV
          value: development
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      volumes:
      - name: storage-volume
        emptyDir: {}
