apiVersion: v1
kind: Service
metadata:
  name: backend-file-store-service
spec:
  selector:
    app: backend-file-store
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort  # Change to LoadBalancer for cloud environments
