version: "3.9"

services:
  server:
    build:
      context: ../server
      dockerfile: ../docker/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../server/storage:/app/storage
    environment:
      - FLASK_ENV=development
